### ISSUE TITLE
Firefox: Most (all) scroll bars don't work.

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1348]
### User Story
Haven't done a thorough check, but when using Firefox with Windows 10, there seems to be a scroll bar for every pane, and none of them are functional. For example:

![image](https://cloud.githubusercontent.com/assets/10427268/20983826/892dc952-bc83-11e6-82a3-d9dd21642c86.png)

Not sure if these examples all stem from the same problem or not, and would be curious to know if they show up with firefox on mac.

**Comment by chiatt** [comment]
@mradamcox This doesn't seem to be an issue on mac (10.12.1), with FF (49.0.2)

**Comment by veuncent** [comment]
I am seeing the same issue on Firefox 51.0.1 (32-bit) (Windows 10).
Also: the left navigation bar disappears when I make the window small. Chrome abides by the min-width rule and keeps the left navigation panel in its smallest format. 

Firefox left, Chrome on the right:
![arches4_firefox_chrome](https://cloud.githubusercontent.com/assets/7893339/22570134/216e65a8-e968-11e6-8f38-4e7fc2993c3d.png)

![arches4_firefox_chrome ii](https://cloud.githubusercontent.com/assets/7893339/22570347/e8ab6e54-e968-11e6-9d10-e17aacdfee1c.png)

![arches4_firefox_chrome iii](https://cloud.githubusercontent.com/assets/7893339/22570352/ed763a7c-e968-11e6-8b4b-0d8642dbdb58.png)

**Comment by chiatt** [comment]
@mradamcox I think this should be resolved with #1346

**Comment by azerbini** [comment]
@chiatt  and @mradamcox actually, this is still not working for us on either Yosemite ( Firefox 51.0.1) or Windows 8.1 (Firefox 52.0.1)

**Comment by mradamcox** [comment]
Ok, I'm closing this as it does seem to be solved for Firefox 51 on Windows 10. @azerbini can you open new tickets for the other operating systems if they are still not working?

**Comment by chiatt** [comment]
@mradamcox @azerbini It looks like the scrollbars have stopped working on FF Windows 10 as well.  I'm going to go ahead and reopen.

**Comment by chiatt** [comment]
@mradamcox Nevermind, I see that @azerbini Created a new issue. I will go ahead and use that one instead. I'll go ahead and close this.
