### ISSUE TITLE
Arches Designer: Menu order

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2013]
### Bug Report
The menus in Resource Editor are not sorted according to the order reflected in Arches Designer, Menu Editor.

#### Expected Behavior
I was expecting that the sort order of menus was dictated by the Menu Editor . 

#### Current Behavior
The menus in Resource Editor are ordered in a seemingly random way.

*Hint: before adding a new menu to the default Heritage Resource Model, sorting happened correctly. The shuffle seemed to have happened after adding a new menu.*

Arches Designer, Menu Editor:
![image](https://cloud.githubusercontent.com/assets/7893339/25401880/ffc1afb2-29c4-11e7-8258-e8db50847d88.png)

Resource Editor menus:
![image](https://cloud.githubusercontent.com/assets/7893339/25401894/0951e3d0-29c5-11e7-85d7-8b604c9513b4.png)

#### Your Arches Information

* Version used: master branch, SHA 5336f7ddc8dbb5c9cbaadd4e951b98e0a06a5cf3 
* Browser Name and version: Chrome Version 58.0.3029.81
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by chiatt** [comment]
@veuncent Hi Vincent - I just merged in a fix. Could you take a look and confirm it's working properly now?

**Comment by veuncent** [comment]
It seems to work mostly fine now, except when I start out with an empty menu (no cards assigned).

In that scenario, the menu is not displayed in the Resource Editor (as expected).
Then when I add a card to that empty menu, the position of this specific menu in the Resource Editor is random. 

The workaround is to move the menu in the Arches Designer. After that, the menu is displayed at the expected position in the menu list. 


Quite an edge case, not a real problem for me.

**Comment by veuncent** [comment]
The issue still persists for me after a pull from master (0fa25c721a49d784c4fb53186acd826c39e60cdb).

The menu order is fine when I have only the default menus, but they are all scrambled as soon as I add a new menu (with a card) to the Resource Model.

**Comment by chiatt** [comment]
@apeters I'm not able to reproduce this issue. Can you take a look?

**Comment by robgaston** [comment]
cannot reproduce
