### ISSUE TITLE
Rich Text Widget: Saved value shows html tags

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#2359]
### Bug Report
Saved data in the rich text widget above the text input box displays html tags in text.

#### Expected Behavior
Saved text should not display html tags.

![screen shot 2017-08-17 at 12 36 00 pm](https://user-images.githubusercontent.com/3038476/29430327-daceab8c-8348-11e7-84c1-e712d5d96030.png)

**Comment by dwuthrich** [comment]
@ryan86 HTML tags still appear.  To recreate: enter a description for a model that uses description in the search results left panel.  Note that HTML tags are present.

**Comment by apeters** [comment]
fixed in the latest

**Comment by dwuthrich** [comment]
@apeters HTML tags still appear in the map panel (e.g.: when cursor hovers over a vector in the map search).  HTML tags also appear in the force directed graph item list.

**Comment by apeters** [comment]
@ryan86 , I've confirmed both of those items @dwuthrich mentioned above.  Attached are some screen shots.
![screen shot 2017-10-04 at 2 22 33 pm](https://user-images.githubusercontent.com/823773/31200389-ad9e1386-a90f-11e7-8f85-bea6c9f6670b.png)
![screen shot 2017-10-04 at 2 23 01 pm](https://user-images.githubusercontent.com/823773/31200388-ad9696f6-a90f-11e7-8b89-2838967f65e6.png)

**Comment by mradamcox** [comment]
#2167 is related and is still on the 4.0.1 release milestone

**Comment by ryan86** [comment]
@dwuthrich I made a commit to fix the html tag issue from 2359, but the related resources card css could be improved.

**Comment by apeters** [comment]
meets requirements
