### ISSUE TITLE
Overlays, map tools do not work in Resource Editor Report Template

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3945]
In the map report template in the Resource editor, it appears that the overlay library isn't working properly.  See: http://recordit.co/U8BEmxSE2v

Note: some overlays (e.g.: search results, hex, heat map) do not appear when selected.  Also the instance geometry seems to be lost when adding resource overlays, causing the "home" button to no longer functions

**Comment by robgaston** [comment]
@dwuthrich I fixed the bug with the overlay editor that your gif shows.  I've also disabled the removal of the main report layer in the header map.

I've also made the map (and image) header template(s) are dynamic in the resource editor report.

re: the layers that you mentioned showing no data (search results, hex, heat map) - this is because these layers only have data on the search map.  perhaps we can hide them on other maps, but that will require some adjustment to our data model, so I think we should handle that as a separate (enhancement) ticket.

**Comment by dwuthrich** [comment]
@robgaston Agree that we should add a ticket for dealing with hex/heat map.  Note that the home button (eg: center map on current instance geometry) still isn't working

**Comment by robgaston** [comment]
@dwuthrich I just merged in a fix for the home button in the report map

**Comment by dwuthrich** [comment]
meets requirements
